export const defaultSurvey:any = {
  'section_a': {
    'a1date':{type: 'date'},
    'a1time':{type: 'time'},
    'a2':{type:'string'},
    'a3':{type:'string'},
    'a4':{type:'string'},
    'a5':{type:'string'},
    'a6':{type:'string'},
    'a7':{type:'string'},
    'a8':{type:'string'},
    'a9':{type:'string'}
  },
  'section_b': {
    _params: {
      _type: 'array',
      _max: 20,
      _id: 'b1'
    },
    'b1': {type: 'string'},
    'b2': {type: 'single_choice', kv: { '1':'M','2':'F'}},
    'b3': {type: 'number'},
    'b4': {type: 'string'},
    'b5': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}}, //s: ['Oui':'Non'], s: ['1':'2']},
    'b6': {type: 'single_choice', kv: {'1':'Conjoint(e)','2':'Fils/Fille','3':'Frère/Sœur','4':'Neveu/Nièce','5':'Petits-fils/filles','6':'Père/Mère'}},
    'b7': {type: 'single_choice', kv: {'1':'Célibataire','2':'Marié mono','3':'Marié poly','4':'Veuf(ve)','5':'Divorcé','6':'Séparé','7':'Union libre'}},
    'b8': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'b9': {type: 'string'}
  },
  'section_c': {
    _params: {
      _type: 'array',
      _max: 'section_b',
      _id: 'b1'
    },
    'code': {type:'string', added: true},
    'c1': {type: 'single_choice', kv: {'10':'Bassa','20':'Francais','30':'Anglais','40':'Autres'}},
    'c2': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'c9'}},
    'c3': {type: 'single_choice', kv: {'1':'Primaire','2':'Secondaire','3':'Universite','4':'Formation','99':'NSP','00':'Pas fait de choix'}},
    'c4': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'c5': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'c6': {type: 'single_choice', kv: {'41': 'Formation professionnelle/technique au secondaire','42':'Formation generale','43':'Formation pour enseignant : ENIET, ENIEG','31':'Université/Formation professionnelle universitaire'}},
    'c7': {type: 'string'},
    'c8': {type: 'single_choice', kv: {'1':'Manque de performance scolaire','2':'Etat de santé'}},
    'c9': {type: 'text'}
  },
  'section_d': {
    _params: {
      _type: 'array',
      _max: 'section_b',
      _id: 'b1'
    },
    'code': {type:'string', added: true},
    'sexe': {type:'string', added: true},
    'age': {type:'string', added: true},
    'd1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'end_subsection'}},
    'd2': {type: 'string'},
    'd3': {type: 'string'},
    'd4': {type: 'single_choice', kv: {'1':"Hôpital public",'2':"Hôpital privé",'3':"Automédication",'4':"Médecine traditionnelle",'5':"Rien"}, jumpTo: {"5":"d7"}},
    'd5a': {type: 'single_choice', kv: {"1":"Plus","2":"Moins","3":"Moyen"}},
    'd5b': {type: 'text'},
    'd6': {type: 'text'},
    'd7': {type: 'single_choice', kv: {"1":"Pas nécessaire","2":"Manque de moyen financier","3":"Distance longue","4":"Absence de soins appropriés","5":"Mauvais accueil","6":"Autres"}},
  },
  'section_e': {
    _params: {
      _type: 'array',
      _max: 'section_b',
      _id: 'b1'
    },
    'e1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'1':'e4'}},
    'e2': {type: 'single_choice', kv: {"1":"Etait malade","2":"Etait en vacances","3":"Etait au repos","4":"Etait à la recherche du travail","5":"A eu un problème","6":"Autres"}},
    'e3': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'1':'e12', '2':'end_subsection'}},
    'e4': {type: 'string'},
    'e5': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Autres"}},
    'e6': {type: 'single_choice', kv: {"1":"Salaire","2":"Paiementen nature","3":"Paiement jour/heure","4":"Aide familiale rémunéré","5":"A mon compte","6":"Autres"}},
    'e7': {type: 'single_choice', kv: {"1":"Prive","2":"Public","3":"Para-publique","4":"Pour le compte d’un employeur"}},
    'e8': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Enseignement","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Autres"}},
    'e9': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e12'}},
    'e10': {type: 'single_choice', kv: {"1":"En prenant un travail supplémentaire","2":"En augmentant les heures et les jours de travail","3":"En réduisant les dépenses","4":"Autres"}},
    'e11': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e13'}},
    'e12': {type: 'single_choice', kv: { "1":"Pas nécessaire","2":"Cas de maladie","3":"Absence de temps","4":"Autres"}},
    'e13': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e22'}},
    'e14': {type: 'single_choice', kv: {"1":"Emploi permanent","2":"Emploi saisonnier","3":"Emploi journalier","4":"Autres"}},
    'e15': {type: 'single_choice', kv: {"1":"Agriculture,élevage,Pêche","2":"Administration(cadres supérieurs,moyens,subalternes,employé,ouvriers,manœuvres,professions libérales)","3":"Commerce","4":"Artisanat","5":"Services domestiques","6":"Forces armées et sécurités","7":"Autres"}},
    'e16': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e18'}},
    'e17': {type: 'single_choice', kv: {"1":"CNPS+Assurance","2":"CNPS","3":"Autres"}},
    'e18': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e19': {type: 'string'},
    'e20': {type: 'single_choice', kv: {"1":"1-3 mois","2":"3-6 mois","3":"6-9mois","4":"9-12mois"}},
    'e21': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e22': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Forces armée et sécurité","11":"Artisanat/Boulanger","12":"Cadres supérieurs,moyens,subalternes,employés,manœuvres,professions libérales","13":"Enseignant","14":"Autres"}},
    'e23': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Fabrication","8":"Réparation","9":"Autres"}},
    'e24': {type: 'string'},
    'e25': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e26': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e32'}},
    'e27': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Artisan","11":"Enseignant","12":"Autres"}},
    'e28': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","7":"Ingénierie","8":"Autres"}},
    'e29': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e30': {type: 'string'},
    'e31': {type: 'string'},
    'e32': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e39'}},
    'e33': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Forces armée et sécurité","11":"Artisanat/Boulanger","12":"Cadres supérieurs,moyens,subalternes,employés,manœuvres,professions libérales","13":"Enseignant","14":"Coiffure","15":"Transporteur","16":"Autres"}},
    'e34': {type: 'string'},
    'e35': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Autres"}},
    'e36': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e37': {type: 'single_choice', kv: {"1":"Faible","2":"Moyen","3":"Passable","4":"Assez-bien","5":"Bien","6":"Tres-Bien"}},
    'e38': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e39': {type: 'text'},
  },
  'section_f': {
    'f1':  {type: 'single_choice', kv: {'1':'Locataire (Paye en argent ou en nature)','2':'Propriétaire avec titre foncier','3':'Propriétaire avec certificat de propriété','4':'Propriétaire avec droit coutumier','5':'Propriétaire avec abandon du droit coutumier','6':'Propriétaire avec certificat d’achat'}},
    'f2a': {type: 'multiple_choice', kv: {'1':'Chambres à coucher','2':'Cuisines','3':'Salle de bain','4':'Salle à manger/Salon'}},
    'f2b': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'f3': {type: 'single_choice', kv: {'1':'Supérieur à 1 Ha','2':'Inférieur à 1 Ha'}},
    'f4': {type: 'single_choice', kv: {'1':'Identique','2':'Pas eu de terre il y’a un an','3':'Plus d’un Ha','4':'Moins d’un Ha'}},
    'f5': {type: 'single_choice', kv: {'1':'Exploitez les terres louées','2':'Exploitez des terres empruntées','3':'Exploitez des terres offertes comme cadeau','4':'Exploitez des terres gagées','5':'Aucune de ces reponses'}, jumpTo: {'5':'f8'}},
    'f6': {type: 'number'},
    'f7': {type: 'single_choice', kv: {'5':'Identique','6':'Pas eu de terre il y’a un an','7':"Pas eu de terre il y’a un an",'8':'Superficie inférieur à 1 hectare','9':'Superficie en mètre carré'}, jumpTo: {'7':'f7_size','8':'f7_size','9':'f7_size'}},
    'f7_size': {type: 'number'},
    'f8_boeufs': {type: 'number'},
    'f8_chevaux': {type: 'number'},
    'f8_vaches': {type: 'number'},
    'f8_autres': {type: 'number'},
    'f9_boeufs': {type: 'number'},
    'f9_chevaux': {type: 'number'},
    'f9_vaches': {type: 'number'},
    'f9_autres': {type: 'number'},
    'f10_moutons': {type: 'number'},
    'f10_chevres': {type: 'number'},
    'f10_porcs': {type: 'number'},
    'f10_boucs': {type: 'number'},
    'f10_autres': {type: 'number'},
    'f11_moutons': {type: 'number'},
    'f11_chevres': {type: 'number'},
    'f11_porcs': {type: 'number'},
    'f11_boucs': {type: 'number'},
    'f11_autres': {type: 'number'},
    'f12': {type: 'single_choice', kv:{'1':'Téléviseur','2':'Poste radio','3':'Cuisinière à gaz','4':'Réchaud à pétrole','5':'Mixeur','6':'Congélateur/frigo','7':'vélo','8':'Moto','9':'Voiture','10':'Pousse-pousse/brouette','11':'Antenne Canalsat','12':'Télephone fixe/ portable','13':'Micro-onde','14':'Pousse-pousse/brouette','15':'Autres'}},
    'f13': {type: 'single_choice', kv:{'1':'Enéo','2':'Energie solaire','3':'Groupe électrogène','4':'Lampe à pétrole','5':'Energie hydraulique','6':'Energie éolienne','7':'Lampes torches','8':'Autres'}},
    'f14': {type: 'single_choice', kv:{'1':'Rarement','2':'Quelques fois','3':'Souvent','4':'Toujours'}},
    'f15': {type: 'single_choice', kv:{'1':'Faible','2':'Moyen','3':'Passable','4':'Assez bien','5':'Bien','6':'Tres bien','7':'Excellent'}},
    'f17': {type: 'single_choice', kv:{'1':'Exterieur du menage','2':'Chef de menage','3':'Epouse chef de menage','4':'Fils/Fille de menage','5':'Neuve/Niece chef de menage','6':'Autres'}},
    'f18': {type: 'single_choice', kv:{'1':'Oui','2':'Non'}, jumpTo:{'1':'section_g__g1'}},
    'f19': {type: 'string'},
  },
  'section_g': {
    'g1': {type: 'single_choice', kv:{ "1":"Toles","2":"Tuiles","3":"Pailles","4":"Feuilles tissees","5":"Autres"}},
    'g2': {type: 'single_choice', kv:{"1":"Parpaing","2":"Brique de terre","3":"Torchis (poto-poto)","4":"Planches","5":"Autres"}},
    'g3a': {type: 'single_choice', kv:{"1":"Robinet","2":"Forage","3":"Puits ferme","4":"Puits ferme et amenage","5":"Bonne fontaine","6":"Source amenagees","7":"Sources ouvertes/non amenagees","8":"Puits ouverts","9":"Lacs","10":"Riviere"}, group:{"Sources d'eau salubre":['1', '2', '3', '4'], "Sources d'eau non salubre":['7','8','9','10']}},
    'g3b': {type: 'single_choice', kv:{'1':'Oui','2':'Non'}},
    'g4': {type: 'single_choice', kv:{"1":"WC avec chasse d’eau et fosse septique","2":"Latrines ordinaires","3":"Latrines à fosse ventilée","4":"Fosse artisanal/canon"}},
    'g5': {type: 'single_choice', kv:{"1":"Electricité","2":"Energie solaire","3":"Gaz","4":"Pétrole","5":"Bois","6":"Charbon"}},
    'g6a': {type: 'single_choice', kv:{"1":"Marchés des produits alimentaires","2":"Marchés des produits cosmétiques","3":"Ecole primaire","4":"Ecole secondaire","5":"Ecole universitaire","6":"Structures de formations","7":"Structure sanitaires","8":"Structures administratives","9":"Points d’eau"}},
    'g6a_1': {type: 'number'},
    'g6a_2': {type: 'number'},
    'g6a_3': {type: 'number'},
    'g6a_4': {type: 'number'},
    'g6a_5': {type: 'number'},
    'g6a_6': {type: 'number'},
    'g6a_7': {type: 'number'},
    'g6a_8': {type: 'number'},
    'g6a_9': {type: 'number'},
    'g6b': {type: 'single_choice', kv:{"1":"Moto","2":"Marche","3":"Taxi","4":"Car","5":"Vélo","6":"Voiture personnelle","7":"Voiture de transport","8":"Train","9":"Bus de ligne","10":"Autres"}},
    'g7': {type: 'string'},
    'g8': {type: 'single_choice', kv:{"1":"Sable+ciment (non lissé)","2":"Sable+ciment (lissé)","3":"Carreaux","4":"Terre nue","5":"Autres"}},
    'g9': {type: 'single_choice', kv:{"1":"Immeuble à appartement","2":"Villa","3":"Maison individuel simple","4":"Maison traditionnel ou case","5":"Hutte","6":"Autres"}},
    'g10': {type: 'single_choice', kv:{"1":"Poubelle","2":"Existence d’un service de ramassage/collecte","3":"Dans la rivière","4":"Autres"}},

  },
  'section_m': {
    'm1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'m4'}},
    'm2': {type: 'multiple_choice', kv: {'1':'Transport','2':'Scolarisation','3':'Factures','4':'Factures(Eau, Electricite)','6':'Intrants/Materiels agricole','7':'Sante','8':'Autres'}, post:[{'1':'m2_transport','2':'m2_scolarisations','3':'m2_vestimentaires','4':'m2_factures','5':'m2_outils_menageres','6':'m2_int_mat_agric','7':'m2_sante','8':'m2_others'}]},
    'm2_transport': {type: 'number'},
    'm2_scolarisations': {type: 'number'},
    'm2_vestimentaires': {type: 'number'},
    'm2_factures': {type: 'number'},
    'm2_outils_menageres': {type: 'number'},
    'm2_int_mat_agric': {type: 'number'},
    'm2_sante': {type: 'number'},
    'm2_others': {type: 'string'},
    'm2_others_value': {type: 'number'},
    'm3': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'm4': {type: 'multiple_choice', kv: {'1':'Bois','2':"Charbon",'3':'Loyer','4':"Eau",'5':"Electricite",'6':'Gaz','7':"Petrole",'8':"Achat de piles",'9':"Autres"}, post:[{'1':'m4_bois','2':'m4_charbon','3':'m4_loyer','4':'m4_eau','5':'m4_electricite','6':'m4_gaz','7':'m4_petrole','8':'m4_pile','9':'m4_others'}]},
    'm4_bois': {type: 'number'},
    'm4_charbon': {type: 'number'},
    'm4_loyer': {type: 'number'},
    'm4_eau': {type: 'number'},
    'm4_electricite': {type: 'number'},
    'm4_gaz': {type: 'number'},
    'm4_petrole': {type: 'number'},
    'm4_pile': {type: 'number'},
    'm4_others': {type: 'string'},
    'm4_others_value': {type: 'number'},
    'm5': {type: 'number'}
  },
  'section_n': {
    'n1': {type: 'multiple_choice', kv: {'1':'Creation des services de soins specialises pour enfants, adultes et personnes de troisieme age', '2':'Rapprochement des services de soins de la population', '3':'Fluidite de la qualite du service dans les soins de sante', '4':'Ouverture des centres traditionnels de sante', '5':'Autre'}, post:{'5':'n1_others'}},
    'n1_others': {type: 'string', hidden:"true"},
    'n2': {type: 'multiple_choice', kv: {'1':'Insertion socioprofessionelles des jeunes apres leurs formations','2':'Creation des structures educatives repondant aux besoins et a la demande de la population','3':'Pour les personnes desoeuvrees et qui desirent poursuivre les etudes, faciliter leur inscription dans les ecoles appropries','4':"Ouverture d'un centre pour apprentissage en langue locale pour les jeunes",'5':"Mettre en place une bibliotheque fonctionnelle pour les apprenants",'6':"Autres" }, post:{'6':'n2_others'}},
    'n2_others': {type: 'string', hidden:"true"},
    'n3': {type: 'single_choice', kv: {'1':'Agro-pastorale','2':'Enseignement','3':'Commerce','4':'Recyclage et gestion des ordures','5':'Administration','6':'Construction','7':'Action sociale','8':'Ingenieurie','9':'Communication','10':'Autres'}, post:{'10':'n3_others'}},
    'n3_others': {type: 'string', hidden:"true"},
    'n4': {type: 'multiple_choice', kv: {'1':"Assurance d'une securite sociale",'2':"Disposition pour payer les conges annuels",'3':"Eviter les licenciements abusifs",'4':"Organiser les concours du meilleur projet par secteur d'activite","5":"Mettre en place les meilleurs projets d'activite","6":"Autres"}, post:{'6':'n4_others'}},
    'n4_others': {type: 'string', hidden:"true"},
    'n5': {type: 'multiple_choice', kv: {'1':"Creation d'une ecole d'agriculture",'2':"Faciliter la procedure d'obtention du titre foncier pour les terres detenues",'3':"Application directe et reconnaissance de la decision du tribunal coutumier en matiere de reglement de litige foncier",'4':"Mettre les agriculteurs en cooperative",'5':"Faciliter et promouvoir l'obtention des intrants naturels des produits agricoles",'6':"Campagne de sensibilisation sur la meteriologie",'7':"Amenager les routes pour les faciliter le deplacement dans les installations les plus proches",'8':"Transformation des produits agricoles sur place",'9':"Mettre sur pied un systeme de conservation des produits agricoles jusqu'a la prochaine recolte",'10':"Autres"}, post:{'10':'n5_others'}},
    'n5_others': {type: 'string', hidden:"true"},
    'n6': {type: 'multiple_choice', kv: {'1':"Construction des logements avec les materiaux locaux",'2':"Construction des logements avec les materiaux contemporains",'3':"Construction des logements ecologiques et durables",'4':'Autres'}, post:{'4':'n6_others'}}, // {action:'display', question:'n6_others', value:'4'}},
    'n6_others': {type: 'string', hidden:"true"}
  }
};

// exports.defaultSurvey = defaultSurvey;
