export const defaultSurvey:any = {
  'section_a': {
    'a1date':{type: 'date'},
    'a1time':{type: 'time'},
    'a2':{type:'string'},
    'a3':{type:'string'},
    'a4':{type:'string'},
    'a5':{type:'string'},
    'a6':{type:'string'},
    'a7':{type:'string'},
    'a8':{type:'string'},
    'a9':{type:'string'}
  },
  'section_b': {
    'b1': {type: 'string'},
    'b2': {type: 'single_choice', kv: { '1':'M', '2':'F'}},
    'b3': {type: 'number'},
    'b4': {type: 'string'},
    'b5': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}}, //, labels: ['Oui', 'Non'], keys: ['1', '2']},
    'b6': {type: 'single_choice', kv: {'1':'Conjoint(e)','2':'Fils/Fille','3':'Frère/Sœur','4':'Neveu/Nièce','5':'Petits-fils/filles','6':'Père/Mère'}},
    'b7': {type: 'single_choice', kv: {'1':'Célibataire','2':'Marié mono','3':'Marié poly','4':'Veuf(ve)','5':'Divorcé','6':'Séparé','7':'Union libre'}},
    'b8': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'b9': {type: 'string'}
  },
  'section_c': {
    'code': {type:'string', added: true},
    'c1': {type: 'single_choice', kv: {'10':'Bassa','20':'Francais','30':'Anglais','40':'Autres'}},
    'c2': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'c9'}},
    'c3': {type: 'single_choice', kv: {'1':'Primaire','2':'Secondaire','3':'Universite','4':'Formation','99':'NSP','00':'Pas fait de choix'}},
    'c4': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'c5': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'c6': {type: 'single_choice', kv: {'41': 'Formation professionnelle/technique au secondaire','42':'Formation generale','43':'Formation pour enseignant : ENIET, ENIEG','31':'Université/Formation professionnelle universitaire'}},
    'c7': {type: 'string'},
    'c8': {type: 'single_choice', kv: {'1':'Manque de performance scolaire', '2':'Etat de santé'}},
    'c9': {type: 'text'}
  },
  'section_d': {
    'code': {type:'string', added: true},
    'sexe': {type:'string', added: true},
    'age': {type:'string', added: true},
    'd1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'end_subsection'}},
    'd2': {type: 'string'},
    'd3': {type: 'string'},
    'd4': {type: 'single_choice', kv: {'1':"Hôpital public",'2':"Hôpital privé",'3':"Automédication",'4':"Médecine traditionnelle",'5':"Rien"}, jumpTo: {"5":"d7"}},
    'd5a': {type: 'single_choice', kv: {"1":"Plus","2":"Moins","3":"Moyen"}},
    'd5b': {type: 'text'},
    'd6': {type: 'text'},
    'd7': {type: 'single_choice', kv: {"1":"Pas nécessaire","2":"Manque de moyen financier","3":"Distance longue","4":"Absence de soins appropriés","5":"Mauvais accueil","6":"Autres"}},
  },
  'section_e': {
    'e1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e2': {type: 'single_choice', kv: {"1":"Etait malade","2":"Etait en vacances","3":"Etait au repos","4":"Etait à la recherche du travail","5":"A eu un problème","6":"Autres"}},
    'e3': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'1':'e12'}},
    'e4': {type: 'string'},
    'e5': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Autres"}},
    'e6': {type: 'single_choice', kv: {"1":"Salaire","2":"Paiementen nature","3":"Paiement jour/heure","4":"Aide familiale rémunéré","5":"A mon compte","6":"Autres"}},
    'e7': {type: 'single_choice', kv: {"1":"Prive","2":"Public","3":"Para-publique","4":"Pour le compte d’un employeur"}},
    'e8': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Enseignement","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Autres"}},
    'e9': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e12'}},
    'e10': {type: 'single_choice', kv: {"1":"En prenant un travail supplémentaire","2":"En augmentant les heures et les jours de travail","3":"En réduisant les dépenses","4":"Autres"}},
    'e11': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e13'}},
    'e12': {type: 'single_choice', kv: { "1":"Pas nécessaire","2":"Cas de maladie","3":"Absence de temps","4":"Autres"}},
    'e13': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e22'}},
    'e14': {type: 'single_choice', kv: {"1":"Emploi permanent","2":"Emploi saisonnier","3":"Emploi journalier","4":"Autres"}},
    'e15': {type: 'single_choice', kv: {"1":"Agriculture,élevage,Pêche","2":"Administration(cadres supérieurs,moyens,subalternes,employé,ouvriers,manœuvres,professions libérales)","3":"Commerce","4":"Artisanat","5":"Services domestiques","6":"Forces armées et sécurités","7":"Autres"}},
    'e16': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e18'}},
    'e17': {type: 'single_choice', kv: {"1":"CNPS+Assurance","2":"CNPS","3":"Autres"}},
    'e18': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e19': {type: 'string'},
    'e20': {type: 'single_choice', kv: {"1":"1-3 mois","2":"3-6 mois","3":"6-9mois","4":"9-12mois"}},
    'e21': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e22': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Forces armée et sécurité","11":"Artisanat/Boulanger","12":"Cadres supérieurs,moyens,subalternes,employés,manœuvres,professions libérales","13":"Enseignant","14":"Autres"}},
    'e23': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Fabrication","8":"Réparation","9":"Autres"}},
    'e24': {type: 'string'},
    'e25': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e26': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e32'}},
    'e27': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Artisan","11":"Enseignant","12":"Autres"}},
    'e28': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","7":"Ingénierie","8":"Autres"}},
    'e29': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e30': {type: 'string'},
    'e31': {type: 'string'},
    'e32': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e39'}},
    'e33': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Forces armée et sécurité","11":"Artisanat/Boulanger","12":"Cadres supérieurs,moyens,subalternes,employés,manœuvres,professions libérales","13":"Enseignant","14":"Coiffure","15":"Transporteur","16":"Autres"}},
    'e34': {type: 'string'},
    'e35': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Autres"}},
    'e36': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e37': {type: 'single_choice', kv: {"1":"Faible","2":"Moyen","3":"Passable","4":"Assez-bien","5":"Bien","6":"Tres-Bien"}},
    'e38': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e39': {type: 'text'},
  }
};

// exports.defaultSurvey = defaultSurvey;
