export const defaultSurvey:any = {
  'section_a': {
    'a1date':{type: 'date'},
    'a1time':{type: 'time'},
    'a2':{type:'string'},
    'a3':{type:'string'},
    'a4':{type:'string'},
    'a5':{type:'string'},
    'a6':{type:'string'},
    'a7':{type:'string'},
    'a8':{type:'string'},
    'a9':{type:'string'}
  },
  'section_b': {
    _params: {
      _type: 'array',
      _max: 20,
      _id: 'b1'
    },
    'b1': {type: 'string'},
    'b2': {type: 'single_choice', kv: { '1':'M','2':'F'}},
    'b3': {type: 'number'},
    'b4': {type: 'string'},
    'b5': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}}, //s: ['Oui':'Non'], s: ['1':'2']},
    'b6': {type: 'single_choice', kv: {'1':'Conjoint(e)','2':'Fils/Fille','3':'Frère/Sœur','4':'Neveu/Nièce','5':'Petits-fils/filles','6':'Père/Mère'}},
    'b7': {type: 'single_choice', kv: {'1':'Célibataire','2':'Marié mono','3':'Marié poly','4':'Veuf(ve)','5':'Divorcé','6':'Séparé','7':'Union libre'}},
    'b8': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'b9': {type: 'string'}
  },
  'section_c': {
    _params: {
      _type: 'array',
      _max: 'section_b',
      _id: 'b1'
    },
    'code': {type:'string', added: true},
    'c1': {type: 'single_choice', kv: {'10':'Bassa','20':'Francais','30':'Anglais','40':'Autres'}},
    'c2': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'c9'}},
    'c3': {type: 'single_choice', kv: {'1':'Primaire','2':'Secondaire','3':'Universite','4':'Formation','99':'NSP','00':'Pas fait de choix'}},
    'c4': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'c5': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'c6': {type: 'single_choice', kv: {'41': 'Formation professionnelle/technique au secondaire','42':'Formation generale','43':'Formation pour enseignant : ENIET, ENIEG','31':'Université/Formation professionnelle universitaire'}},
    'c7': {type: 'string'},
    'c8': {type: 'single_choice', kv: {'1':'Manque de performance scolaire','2':'Etat de santé'}},
    'c9': {type: 'text'}
  },
  'section_d': {
    _params: {
      _type: 'array',
      _max: 'section_b',
      _id: 'b1'
    },
    'code': {type:'string', added: true},
    'sexe': {type:'string', added: true},
    'age': {type:'string', added: true},
    'd1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'end_subsection'}},
    'd2': {type: 'string'},
    'd3': {type: 'string'},
    'd4': {type: 'single_choice', kv: {'1':"Hôpital public",'2':"Hôpital privé",'3':"Automédication",'4':"Médecine traditionnelle",'5':"Rien"}, jumpTo: {"5":"d7"}},
    'd5a': {type: 'single_choice', kv: {"1":"Plus","2":"Moins","3":"Moyen"}},
    'd5b': {type: 'text'},
    'd6': {type: 'text'},
    'd7': {type: 'single_choice', kv: {"1":"Pas nécessaire","2":"Manque de moyen financier","3":"Distance longue","4":"Absence de soins appropriés","5":"Mauvais accueil","6":"Autres"}},
  },
  'section_e': {
    _params: {
      _type: 'array',
      _max: 'section_b',
      _id: 'b1'
    },
    'e1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'1':'e4'}},
    'e2': {type: 'single_choice', kv: {"1":"Etait malade","2":"Etait en vacances","3":"Etait au repos","4":"Etait à la recherche du travail","5":"A eu un problème","6":"Autres"}},
    'e3': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'1':'e12', '2':'end_subsection'}},
    'e4': {type: 'string'},
    'e5': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Autres"}},
    'e6': {type: 'single_choice', kv: {"1":"Salaire","2":"Paiementen nature","3":"Paiement jour/heure","4":"Aide familiale rémunéré","5":"A mon compte","6":"Autres"}},
    'e7': {type: 'single_choice', kv: {"1":"Prive","2":"Public","3":"Para-publique","4":"Pour le compte d’un employeur"}},
    'e8': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Enseignement","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Autres"}},
    'e9': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e12'}},
    'e10': {type: 'single_choice', kv: {"1":"En prenant un travail supplémentaire","2":"En augmentant les heures et les jours de travail","3":"En réduisant les dépenses","4":"Autres"}},
    'e11': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e13'}},
    'e12': {type: 'single_choice', kv: { "1":"Pas nécessaire","2":"Cas de maladie","3":"Absence de temps","4":"Autres"}},
    'e13': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e22'}},
    'e14': {type: 'single_choice', kv: {"1":"Emploi permanent","2":"Emploi saisonnier","3":"Emploi journalier","4":"Autres"}},
    'e15': {type: 'single_choice', kv: {"1":"Agriculture,élevage,Pêche","2":"Administration(cadres supérieurs,moyens,subalternes,employé,ouvriers,manœuvres,professions libérales)","3":"Commerce","4":"Artisanat","5":"Services domestiques","6":"Forces armées et sécurités","7":"Autres"}},
    'e16': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e18'}},
    'e17': {type: 'single_choice', kv: {"1":"CNPS+Assurance","2":"CNPS","3":"Autres"}},
    'e18': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e19': {type: 'string'},
    'e20': {type: 'single_choice', kv: {"1":"1-3 mois","2":"3-6 mois","3":"6-9mois","4":"9-12mois"}},
    'e21': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e22': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Forces armée et sécurité","11":"Artisanat/Boulanger","12":"Cadres supérieurs,moyens,subalternes,employés,manœuvres,professions libérales","13":"Enseignant","14":"Autres"}},
    'e23': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Fabrication","8":"Réparation","9":"Autres"}},
    'e24': {type: 'string'},
    'e25': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e26': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e32'}},
    'e27': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Artisan","11":"Enseignant","12":"Autres"}},
    'e28': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","7":"Ingénierie","8":"Autres"}},
    'e29': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e30': {type: 'string'},
    'e31': {type: 'string'},
    'e32': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'e39'}},
    'e33': {type: 'single_choice', kv: {"1":"Electricien","2":"Commerçant","3":"Agriculteur/Eleveur","4":"Domestique/Ménagère","5":"Chasseur","6":"Bucheron","7":"Couturier","8":"Macon","9":"Secretaire","10":"Forces armée et sécurité","11":"Artisanat/Boulanger","12":"Cadres supérieurs,moyens,subalternes,employés,manœuvres,professions libérales","13":"Enseignant","14":"Coiffure","15":"Transporteur","16":"Autres"}},
    'e34': {type: 'string'},
    'e35': {type: 'single_choice', kv: {"1":"Agropastorale","2":"Education","3":"Administration","4":"Construction","5":"Action sociale","6":"Ingénierie","7":"Autres"}},
    'e36': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e37': {type: 'single_choice', kv: {"1":"Faible","2":"Moyen","3":"Passable","4":"Assez-bien","5":"Bien","6":"Tres-Bien"}},
    'e38': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'e39': {type: 'text'},
  },
  'section_f': {
    'f1':  {type: 'single_choice', kv: {'1':'Locataire (Paye en argent ou en nature)','2':'Propriétaire avec titre foncier','3':'Propriétaire avec certificat de propriété','4':'Propriétaire avec droit coutumier','5':'Propriétaire avec abandon du droit coutumier','6':'Propriétaire avec certificat d’achat'}},
    'f2a': {type: 'multiple_choice', kv: {'1':'Chambres à coucher','2':'Cuisines','3':'Salle de bain','4':'Salle à manger/Salon'}},
    'f2b': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'f3': {type: 'single_choice', kv: {'1':'Supérieur à 1 Ha','2':'Inférieur à 1 Ha'}},
    'f4': {type: 'single_choice', kv: {'1':'Identique','2':'Pas eu de terre il y’a un an','3':'Plus d’un Ha','4':'Moins d’un Ha'}},
    'f5': {type: 'single_choice', kv: {'1':'Exploitez les terres louées','2':'Exploitez des terres empruntées','3':'Exploitez des terres offertes comme cadeau','4':'Exploitez des terres gagées','5':'Aucune de ces reponses'}, jumpTo: {'5':'f8'}},
    'f6': {type: 'number'},
    'f7': {type: 'single_choice', kv: {'5':'Identique','6':'Pas eu de terre il y’a un an','7':"Pas eu de terre il y’a un an",'8':'Superficie inférieur à 1 hectare','9':'Superficie en mètre carré'}, jumpTo: {'7':'f7_size','8':'f7_size','9':'f7_size'}},
    'f7_size': {type: 'number'},
    'f8_boeufs': {type: 'number'},
    'f8_chevaux': {type: 'number'},
    'f8_vaches': {type: 'number'},
    'f8_autres': {type: 'number'},
    'f9_boeufs': {type: 'number'},
    'f9_chevaux': {type: 'number'},
    'f9_vaches': {type: 'number'},
    'f9_autres': {type: 'number'},
    'f10_moutons': {type: 'number'},
    'f10_chevres': {type: 'number'},
    'f10_porcs': {type: 'number'},
    'f10_boucs': {type: 'number'},
    'f10_autres': {type: 'number'},
    'f11_moutons': {type: 'number'},
    'f11_chevres': {type: 'number'},
    'f11_porcs': {type: 'number'},
    'f11_boucs': {type: 'number'},
    'f11_autres': {type: 'number'},
    'f12': {type: 'single_choice', kv:{'1':'Téléviseur','2':'Poste radio','3':'Cuisinière à gaz','4':'Réchaud à pétrole','5':'Mixeur','6':'Congélateur/frigo','7':'vélo','8':'Moto','9':'Voiture','10':'Pousse-pousse/brouette','11':'Antenne Canalsat','12':'Télephone fixe/ portable','13':'Micro-onde','14':'Pousse-pousse/brouette','15':'Autres'}},
    'f13': {type: 'single_choice', kv:{'1':'Enéo','2':'Energie solaire','3':'Groupe électrogène','4':'Lampe à pétrole','5':'Energie hydraulique','6':'Energie éolienne','7':'Lampes torches','8':'Autres'}},
    'f14': {type: 'single_choice', kv:{'1':'Rarement','2':'Quelques fois','3':'Souvent','4':'Toujours'}},
    'f15': {type: 'single_choice', kv:{'1':'Faible','2':'Moyen','3':'Passable','4':'Assez bien','5':'Bien','6':'Tres bien','7':'Excellent'}},
    'f17': {type: 'single_choice', kv:{'1':'Exterieur du menage','2':'Chef de menage','3':'Epouse chef de menage','4':'Fils/Fille de menage','5':'Neuve/Niece chef de menage','6':'Autres'}},
    'f18': {type: 'single_choice', kv:{'1':'Oui','2':'Non'}, jumpTo:{'1':'section_g__g1'}},
    'f19': {type: 'string'},
  },
  'section_g': {
    'g1': {type: 'single_choice', kv:{ "1":"Toles","2":"Tuiles","3":"Pailles","4":"Feuilles tissees","5":"Autres"}},
    'g2': {type: 'single_choice', kv:{"1":"Parpaing","2":"Brique de terre","3":"Torchis (poto-poto)","4":"Planches","5":"Autres"}},
    'g3a': {type: 'single_choice', kv:{"1":"Robinet","2":"Forage","3":"Puits ferme","4":"Puits ferme et amenage","5":"Bonne fontaine","6":"Source amenagees","7":"Sources ouvertes/non amenagees","8":"Puits ouverts","9":"Lacs","10":"Riviere"}, group:{"Sources d'eau salubre":['1', '2', '3', '4'], "Sources d'eau non salubre":['7','8','9','10']}},
    'g3b': {type: 'single_choice', kv:{'1':'Oui','2':'Non'}},
    'g4': {type: 'single_choice', kv:{"1":"WC avec chasse d’eau et fosse septique","2":"Latrines ordinaires","3":"Latrines à fosse ventilée","4":"Fosse artisanal/canon"}},
    'g5': {type: 'single_choice', kv:{"1":"Electricité","2":"Energie solaire","3":"Gaz","4":"Pétrole","5":"Bois","6":"Charbon"}},
    'g6a': {type: 'single_choice', kv:{"1":"Marchés des produits alimentaires","2":"Marchés des produits cosmétiques","3":"Ecole primaire","4":"Ecole secondaire","5":"Ecole universitaire","6":"Structures de formations","7":"Structure sanitaires","8":"Structures administratives","9":"Points d’eau"}},
    'g6a_1': {type: 'number'},
    'g6a_2': {type: 'number'},
    'g6a_3': {type: 'number'},
    'g6a_4': {type: 'number'},
    'g6a_5': {type: 'number'},
    'g6a_6': {type: 'number'},
    'g6a_7': {type: 'number'},
    'g6a_8': {type: 'number'},
    'g6a_9': {type: 'number'},
    'g6b': {type: 'single_choice', kv:{"1":"Moto","2":"Marche","3":"Taxi","4":"Car","5":"Vélo","6":"Voiture personnelle","7":"Voiture de transport","8":"Train","9":"Bus de ligne","10":"Autres"}},
    'g7': {type: 'string'},
    'g8': {type: 'single_choice', kv:{"1":"Sable+ciment (non lissé)","2":"Sable+ciment (lissé)","3":"Carreaux","4":"Terre nue","5":"Autres"}},
    'g9': {type: 'single_choice', kv:{"1":"Immeuble à appartement","2":"Villa","3":"Maison individuel simple","4":"Maison traditionnel ou case","5":"Hutte","6":"Autres"}},
    'g10': {type: 'single_choice', kv:{"1":"Poubelle","2":"Existence d’un service de ramassage/collecte","3":"Dans la rivière","4":"Autres"}},

  },
  'section_h': {
    _params: {
      _type: 'array',
      _max: 'section_b',
      _id: 'b1'
    },
    'h1': {type:'data'},
    'h2': {type:'string'},
    'h3': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'h4': {type: 'multiple_choice', kv: {'1':'Malformations','2':'Malnutritions','3':'Deficients visuels','4':'Deficients auditifs','5':'Deficients de langage','6':'Hernies','7':'Kystes','8':'Pas de handicap','9':'Autres'},post:{'9':'h4_others'}},
    'h4_others':{type:'string', hidden: true},
    'h5_poids':{type:'number'},
    'h5_taille':{type:'number'},
    'h6': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'h7': {type: 'single_choice', kv: {'1':'Membre menage','2':'Famille','3':'Proche','4':'Autres'},post:{'4':'h7_others'}},
    'h7_others':{type:'string', hidden: true},
  },
  'section_i': {
    'i1': {type:'multiple_choice', kv:{'1':'Frais de scolarite','2':'Livres et fournitures','3':'Uniformes scolaires','4':'Frais de transport scolaire','5':"Cotisation des parents d'eleves",'6':'Autres cotisation scolaires'},post:{'1':'i1_frais_scolarite','2':'i1_livre_fourniture_scolaire','3':'i1_uniforme_scolaires','4':'i1_frais_transport_scolaire','5':'i1_ape','6':'i1_others'}},
    'i1_frais_scolarite': {type:'number', hidden:true},
    'i1_livre_fourniture_scolaire': {type:'number', hidden:true},
    'i1_uniforme_scolaires': {type:'number', hidden:true},
    'i1_frais_transport_scolaire': {type:'number', hidden:true},
    'i1_ape': {type:'number', hidden:true},
    'i1_others': {type:'number', hidden:true},
    'i2': {type:'multiple_choice', kv:{'1':'Frais de scolarite','2':'Livres et fournitures','3':'Uniformes scolaires','4':'Frais de transport scolaire','5':"Cotisation des parents d'eleves",'6':'Autres cotisation scolaires'},post:{'1':'i2_frais_scolarite','2':'i2_livre_fourniture_scolaire','3':'i2_uniforme_scolaires','4':'i2_frais_transport_scolaire','5':'i2_ape','6':'i2_others'}},
    'i2_frais_scolarite': {type:'number', hidden:true},
    'i2_livre_fourniture_scolaire': {type:'number', hidden:true},
    'i2_uniforme_scolaires': {type:'number', hidden:true},
    'i2_frais_transport_scolaire': {type:'number', hidden:true},
    'i2_ape': {type:'number', hidden:true},
    'i2_others': {type:'number', hidden:true},
    'i3': {type:'multiple_choice', kv:{'1':"Frais d'analyse medicale",'2':"Frais de consultation medicale",'3':"Medicaments",'4':"Frais d'hospitalisation",'5':'Autres services medicaux'},post:{'1':'i3_frais_analyse','2':'i3_frais_consultation_medicale','3':'i3_medicaments','4':'i3_frais_hospitalisation','5':'i3_others'}},
    'i3_frais_analyse': {type:'number',hidden:true},
    'i3_frais_consultation_medicale': {type:'number',hidden:true},
    'i3_medicaments': {type:'number',hidden:true},
    'i3_frais_hospitalisation': {type:'number',hidden:true},
    'i3_others': {type:'number',hidden:true},
    'i4': {type:'multiple_choice', kv:{'1':"Semences",'2':"Engrais",'3':"Produits phytosanitaires",'4':"Mains d'oeuvres",'5':'Reparation du materiel agricole','6':"Location/achat du materiel agricole","7":'Autres'}, post:{'1':'i4_semences','2':'i4_engrais','3':'i4_produits_phytosanitaires','4':'i4_mains_oeuvres','5':'i4_reparation_materiels_agricole','6':'i4_loc_achat_materiels_agricole','7':'i4_others'}},
    'i4_semences': {type:'number',hidden:true},
    'i4_engrais': {type:'number',hidden:true},
    'i4_produits_phytosanitaires': {type:'number',hidden:true},
    'i4_mains_oeuvres': {type:'number',hidden:true},
    'i4_reparation_materiels_agricole': {type:'number',hidden:true},
    'i4_loc_achat_materiels_agricole': {type:'number',hidden:true},
    'i4_others': {type:'number',hidden:true},
  },
  'section_j': {
    'j1_cultives': {type: 'multiple_choice', kv: {'1':'Mais','2':'Manioc','3':'Banane plantain','4':'Macabo','5':'Taro','6':'Ignames','7':'Patates','8':'Piments','9':'Pistaches','10':'Haricots','11':'Cacao','12':'Palmier a huile','13':'Cafe','14':'Okok','15':'Tomates','16':'Carottes','17':'Autres'},post:{'17':'j1_others'}},
    'j1_others': {type:'string'},
    'j1_vendus': {type: 'multiple_choice', kv: {'1':'Mais','2':'Manioc','3':'Banane plantain','4':'Macabo','5':'Taro','6':'Ignames','7':'Patates','8':'Piments','9':'Pistaches','10':'Haricots','11':'Cacao','12':'Palmier a huile','13':'Cafe','14':'Okok','15':'Tomates','16':'Carottes','17':'Autres'},post:{'1':'j1_mais','2':'j1_manioc','3':'j1_banane_plantain','4':'j1_macabo','5':'j1_taro','6':'j1_iganmes','7':'j1_patates','8':'j1_piments','9':'j1_pistaches','10':'j1_haricots','11':'j1_cacao','12':'j1_palmier_huile','13':'j1_cafe','14':'j1_okok','15':'j1_tomates','16':'j1_carottes','17':'j1_others_value'}},
    'j1_mais': {type:'number'},
    'j1_manioc': {type:'number'},
    'j1_banane_plantain': {type:'number'},
    'j1_macabo': {type:'number'},
    'j1_taro': {type:'number'},
    'j1_iganmes': {type:'number'},
    'j1_patates': {type:'number'},
    'j1_piments': {type:'number'},
    'j1_pistaches': {type:'number'},
    'j1_haricots': {type:'number'},
    'j1_cacao': {type:'number'},
    'j1_palmier_huile': {type:'number'},
    'j1_cafe': {type:'number'},
    'j1_okok': {type:'number'},
    'j1_tomates': {type:'number'},
    'j1_carottes': {type:'number'},
    'j1_others_value': {type:'number'},
    'j2_mais': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_manioc': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_banane_plantain': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_macabo': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_taro': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_iganmes': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_patates': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_piments': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_pistaches': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_haricots': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_cacao': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_palmier_huile': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_cafe': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_okok': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_tomates': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j2_carottes': {type: 'single_choice', kv: {'1':'Marche', '2':'Negociants','3':'Cooperative','4':'Office de Communication','5':"Sillionneur d'achat et de vente"}},
    'j3': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'j4': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'j5': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'j7'}},
    'j6': {type: 'single_choice', kv: {'1':"Manque de moyens financiers",'2':'Engrais chers','3':'Pas besoins des engrais','4':'Autres'},post:{'4':'j6_others'}},
    'j6_others': {type: 'string'},
    'j7': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'j9'}},
    'j8': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'j9': {type: 'single_choice', kv: {'1':'Pas besoin','2':'As deja les moyens','3':'Pas de structure pour credit agricole','4':'Autres'}, post:{'4':'j9_others'}},
    'j9_others': {type: 'string'},
    'j10': {type: 'number'},
    'j11': {type: 'multiple_choice', kv: {'1':'Machette','2':'Houe','3':'Pioche','4':'Daba','5':'Tracteur','6':'Pompe a moteur','7':'Autres'}, post:{'7':'j11_others'}},
    'j11_others': {type:'string'}
  },
  'section_k': {
    'k1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'end_subsection'}},
    'k2': {type: 'single_choice', kv: {'1':'Elevage','2':'Chasse','3':'Peche','4':'Transport','5':'Commerce','6':'Enseignement','7':'Coiffure','8':'Transport','9':'Electricite','10':'Macon','11':'Domestique/Menager','12':'Force armee et securite','13':'Buvette/restauration','14':'Autres'}, post:{'14':'k2_others'}},
    'k2_others': {type: 'string', hidden: true},
    'k3': {type: 'string'},
    'k4': {type: 'number'},
    'k5': {type: 'number'},
    'k6': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'k8'}},
    'k7': {type: 'number'},
    'k8': {type: 'number'},
    'k9': {type: 'number'},
    'k10': {type: 'number'},
    'k11': {type: 'number'},
    'k12': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'end_subsection'}},
    'k13': {type: 'number'},
    'k14': {type: 'single_choice', kv: {'1':"Augmentation des capitaux",'2':"Augmentation des partenaires",'3':'Forte demande de la clientele','4':'Augmentation des produits de vente','5':'Autres'}, post: {'5':'k14_others'}},
    'k14_others': {type: 'string', hidden: true},
    'k15': {type: 'multiple_choice', kv: {'1':"Jeux du hasard (Pari-foot et PMUC)",'2':"Primes",'3':'Cotisations/Tontine','4':'Heures supplémentaires','5':'Autres'}, post: {'5':'k15_others'}},
    'k15_others': {type: 'string', hidden: true},
  },
  'section_l': {
    'l1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'l4'}},
    'l2': {type: 'multiple_choice', kv:{'1':'Macabo','2':'Manioc','3':'Igname','4':'Patate','5':'Taro','6':'Plantains','7':'Poissons','8':'Viandes','9':'Gombo','10':'Arachides','11':'Mais','12':'Haricots','13':'Pistache','14':'Legumes','15':'Autres','99':'Ne sait pas'},post:{'1':'l2_macabo','2':'l2_manioc','3':'l2_iganmes','4':'l2_patates','5':'l2_taro','6':'l2_plantains','7':'l2_poissons','8':'l2_viandes','9':'l2_gombo','10':'l2_arachides','11':'l2_mais','12':'l2_haricots','13':'l2_pistaches','14':'l2_legumes','15':['l2_others', 'l2_others_value']}},
    'l2_others': {type: 'string', hidden: true},
    'l2_macabo': {type: 'number', hidden: true},
    'l2_manioc': {type: 'number', hidden: true},
    'l2_iganmes': {type: 'number', hidden: true},
    'l2_patates': {type: 'number', hidden: true},
    'l2_taro': {type: 'number', hidden: true},
    'l2_plantains': {type: 'number', hidden: true},
    'l2_poissons': {type: 'number', hidden: true},
    'l2_viandes': {type: 'number', hidden: true},
    'l2_gombo': {type: 'number', hidden: true},
    'l2_arachides': {type: 'number', hidden: true},
    'l2_mais': {type: 'number', hidden: true},
    'l2_haricots': {type: 'number', hidden: true},
    'l2_pistaches': {type: 'number', hidden: true},
    'l2_legumes': {type: 'number', hidden: true},
    'l2_others_value': {type: 'number', hidden: true},
    'l4':{type: 'multiple_choice', kv:{'1':'Macabo','2':'Manioc','3':'Igname','4':'Patate','5':'Taro','6':'Plantains','7':'Poissons','8':'Viandes','9':'Gombo','10':'Arachides','11':'Mais','12':'Haricots','13':'Pistache','14':'Legumes','15':'Autres','99':'Ne sait pas'}}
  },
  'section_m': {
    'm1': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}, jumpTo: {'2':'m4'}},
    'm2': {type: 'multiple_choice', kv: {'1':'Transport','2':'Scolarisation','3':'Factures','4':'Factures(Eau, Electricite)','6':'Intrants/Materiels agricole','7':'Sante','8':'Autres'}, post:{'1':'m2_transport','2':'m2_scolarisations','3':'m2_vestimentaires','4':'m2_factures','5':'m2_outils_menageres','6':'m2_int_mat_agric','7':'m2_sante','8':['m2_others','m2_others_value']}},
    'm2_others': {type: 'string', hidden: true},
    'm2_transport': {type: 'number', hidden: true},
    'm2_scolarisations': {type: 'number', hidden: true},
    'm2_vestimentaires': {type: 'number', hidden: true},
    'm2_factures': {type: 'number', hidden: true},
    'm2_outils_menageres': {type: 'number', hidden: true},
    'm2_int_mat_agric': {type: 'number', hidden: true},
    'm2_sante': {type: 'number', hidden: true},
    'm2_others_value': {type: 'number', hidden: true},
    'm3': {type: 'single_choice', kv: {'1':'Oui','2':'Non'}},
    'm4': {type: 'multiple_choice', kv: {'1':'Bois','2':"Charbon",'3':'Loyer','4':"Eau",'5':"Electricite",'6':'Gaz','7':"Petrole",'8':"Achat de piles",'9':"Autres"}, post:{'1':'m4_bois','2':'m4_charbon','3':'m4_loyer','4':'m4_eau','5':'m4_electricite','6':'m4_gaz','7':'m4_petrole','8':'m4_pile','9':'m4_others'}},
    'm4_bois': {type: 'number', hidden: true},
    'm4_charbon': {type: 'number', hidden: true},
    'm4_loyer': {type: 'number', hidden: true},
    'm4_eau': {type: 'number', hidden: true},
    'm4_electricite': {type: 'number', hidden: true},
    'm4_gaz': {type: 'number', hidden: true},
    'm4_petrole': {type: 'number', hidden: true},
    'm4_pile': {type: 'number', hidden: true},
    'm4_others': {type: 'string', hidden: true},
    'm4_others_value': {type: 'number', hidden: true},
    'm5': {type: 'number'}
  },
  'section_n': {
    'n1': {type: 'multiple_choice', kv: {'1':'Creation des services de soins specialises pour enfants, adultes et personnes de troisieme age', '2':'Rapprochement des services de soins de la population', '3':'Fluidite de la qualite du service dans les soins de sante', '4':'Ouverture des centres traditionnels de sante', '5':'Autre'}, post:{'5':'n1_others'}},
    'n1_others': {type: 'string', hidden:"true"},
    'n2': {type: 'multiple_choice', kv: {'1':'Insertion socioprofessionelles des jeunes apres leurs formations','2':'Creation des structures educatives repondant aux besoins et a la demande de la population','3':'Pour les personnes desoeuvrees et qui desirent poursuivre les etudes, faciliter leur inscription dans les ecoles appropries','4':"Ouverture d'un centre pour apprentissage en langue locale pour les jeunes",'5':"Mettre en place une bibliotheque fonctionnelle pour les apprenants",'6':"Autres" }, post:{'6':'n2_others'}},
    'n2_others': {type: 'string', hidden:"true"},
    'n3': {type: 'single_choice', kv: {'1':'Agro-pastorale','2':'Enseignement','3':'Commerce','4':'Recyclage et gestion des ordures','5':'Administration','6':'Construction','7':'Action sociale','8':'Ingenieurie','9':'Communication','10':'Autres'}, post:{'10':'n3_others'}},
    'n3_others': {type: 'string', hidden:"true"},
    'n4': {type: 'multiple_choice', kv: {'1':"Assurance d'une securite sociale",'2':"Disposition pour payer les conges annuels",'3':"Eviter les licenciements abusifs",'4':"Organiser les concours du meilleur projet par secteur d'activite","5":"Mettre en place les meilleurs projets d'activite","6":"Autres"}, post:{'6':'n4_others'}},
    'n4_others': {type: 'string', hidden:"true"},
    'n5': {type: 'multiple_choice', kv: {'1':"Creation d'une ecole d'agriculture",'2':"Faciliter la procedure d'obtention du titre foncier pour les terres detenues",'3':"Application directe et reconnaissance de la decision du tribunal coutumier en matiere de reglement de litige foncier",'4':"Mettre les agriculteurs en cooperative",'5':"Faciliter et promouvoir l'obtention des intrants naturels des produits agricoles",'6':"Campagne de sensibilisation sur la meteriologie",'7':"Amenager les routes pour les faciliter le deplacement dans les installations les plus proches",'8':"Transformation des produits agricoles sur place",'9':"Mettre sur pied un systeme de conservation des produits agricoles jusqu'a la prochaine recolte",'10':"Autres"}, post:{'10':'n5_others'}},
    'n5_others': {type: 'string', hidden:"true"},
    'n6': {type: 'multiple_choice', kv: {'1':"Construction des logements avec les materiaux locaux",'2':"Construction des logements avec les materiaux contemporains",'3':"Construction des logements ecologiques et durables",'4':'Autres'}, post:{'4':'n6_others'}}, // {action:'display', question:'n6_others', value:'4'}},
    'n6_others': {type: 'string', hidden:"true"}
  }
};

// exports.defaultSurvey = defaultSurvey;
